[package]
name = "biliroaming_rust_server"
version = "0.1.33"
edition = "2021"
author = "P CH"

[dependencies]
chrono = "0.4.19"
curl = "0.4.43"
actix-web = "4.1.0"
qstring = "0.7.2"
md5 = "0.7.0"
json = "0.12.4"
serde_json = "1.0.82"
serde = {version ="1.0.139",features = ["derive"]}
deadpool = "0.9.5"
deadpool-redis = "0.10.2"
crossbeam-channel = "0.5.6"
#openssl = { version = "0.10", features = ["vendored"] }

[profile.fast]
inherits = "release"
opt-level = 3 
debug = false 
split-debuginfo = 'off' 
debug-assertions = false 
overflow-checks = false 
lto = true 
panic = 'unwind' 
incremental = false 
codegen-units = 1 
rpath = false